org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.cache.cleanup = false

loom.platform=neoforge

group = team.cagayakegirls
mod_id = servux
mod_name = Servux
author = masa
mod_file_name = servux-neoforge

# Current mod version
mod_version = 0.5.0

# Minecraft, Fabric Loader and API and mappings versions
minecraft_version_out = 26.1.2
minecraft_version = 26.1.2

neoforge_version = 26.1.2.67-beta
networking_api_version = 0.1.0-alpha.1
foxified_classtweaker_version = 0.1.0-alpha.3
