org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.cache.cleanup = false

loom.platform=neoforge

group = team.cagayakegirls
mod_id = servux
mod_name = Servux
author = masa
mod_file_name = servux-neoforge

# Current mod version
mod_version = 0.5.1

# Minecraft, Fabric Loader and API and mappings versions
minecraft_version_out = 26.2
minecraft_version = 26.2

neoforge_version = 26.2.0.37-beta
networking_api_version = 0.2.0+mc26.2
foxified_classtweaker_version = 0.1.0-alpha.4

# Luck Permissions API (https://github.com/lucko/fabric-permissions-api)
fabric_permissions_api_version = 0.7.0
