org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.cache.cleanup = false

loom.platform=neoforge

group = team.cagayakegirls
mod_id = servux
mod_name = Servux
author = masa
mod_file_name = servux-neoforge

# Current mod version
mod_version = 0.4.1

# Minecraft, Fabric Loader and API and mappings versions
minecraft_version_out = 1.21.11
minecraft_version = 1.21.11

neoforge_version = 21.11.42
fabric_api_version = 0.140.0+2.2.5+1.21.11

# Luck Permissions API (https://github.com/lucko/fabric-permissions-api)
fabric_permissions_api_version = 0.1.0+mc1.21.9
